### ISSUE TITLE
Ability to provide source code, release notes, and reviewer notes

### ISSUE THREAD

**Issue by alandtse** [tophat/semantic-release-firefox-add-on#178]
**Is your feature request related to a problem? Please describe.**
Firefox AMO sometimes requests the upload of source code and instructions on how to build the code. Also, it'd be nice to provide release notes but that's less critical in my view then the stuff reviewers need.

**Describe the solution you'd like**
There should be a publish parameter for both fields.

**Describe alternatives you've considered**
Right now it's a manual workaround to go to the AMO page, and edit the pending release.

**Additional context**

**Comment by iamogbz** [comment]
@alandtse welcome! thanks for contributing. Could you please add some additional context on how this is supported via the `web-ext` tool or if it's only available via the browser AMO page. Looking at https://extensionworkshop.com/documentation/publish/source-code-submission/#source-code-checklist seems like just including additional files in the `sourceDir` would satisfy the conditions.
